version: '3'

services:
  fileserver:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/root/uploads
    environment:
      - PORT=8080
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fileserver
    restart: always